name: Deploy to Build Branch

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install 

      - name: Deploy to build branch
        run: |
          npm run build
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
          git checkout -B build
          shopt -s extglob
          rm -rf !(dist|.*)
          cp -R ./dist/* .
          git add .
          git commit -m "Deploy to build branch"
          git push --force origin build
